# Generated by Django 4.1.1 on 2022-09-14 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('documentId', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='DocumentId')),
                ('name', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('cellularPhone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=20, verbose_name='Role')),
                ('password', models.CharField(max_length=8, verbose_name='Password')),
                ('assignDoctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_document4', to=settings.AUTH_USER_MODEL)),
                ('assignNurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_document5', to=settings.AUTH_USER_MODEL)),
                ('assignRelative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_document6', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vitalSignsID', models.AutoField(default=10, primary_key=True, serialize=False)),
                ('oximetry', models.FloatField(default=99)),
                ('respiratoryRate', models.FloatField(default=99)),
                ('heartRate', models.FloatField(default=99)),
                ('temperature', models.FloatField(default=49)),
                ('diastolicBloodPressure', models.FloatField(default=199)),
                ('systolicBloodPressure', models.FloatField(default=199)),
                ('bloodGlucose', models.FloatField(default=299)),
                ('vitalSignsDate', models.DateTimeField()),
                ('patient_documentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_document2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('diagnosticId', models.AutoField(primary_key=True, serialize=False)),
                ('patientDiagnostic', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('patient_documentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_document1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
