# Generated by Django 4.1.1 on 2022-09-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_user_assigndoctor_alter_user_assignnurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documentId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='DocumentId'),
        ),
    ]
