# Generated by Django 4.1.1 on 2022-09-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0003_alter_user_documentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Password"),
        ),
    ]
